### ISSUE TITLE
Includes in the Installer Build Spec

### ISSUE THREAD

**Issue by clendon-gibson** [ni/rad#5]
In the installer build spec for RAD NI System Configuration is included, but NI CompactRIO Runtime is not. The later is required to allow systems to work with newer cRIOs over their USB connection.

**Comment by SparkingSpork** [comment]
I believe this is intentional. We built RAD with the minimum additional installers needed to run. As a LabVIEW-Built installer will not allow "optional" installers, we have to pick between everyone getting CompactRIO (and increasing the installer size significantly) or providing the bare minimum for the most common use case. 

We list and link to optional installers (CompactRIO for full driver functionality and NI System Configuration for just NI MAX) in the [RAD White Paper](http://www.ni.com/example/30986/en/). 

Additionally, the USB LAN adapter is in my experience mainly used for initial connection to the CompactRIO and not as commonly for deployment or programming. We may reevaluate this as an issue in the future, but for now I'm considering this expected. It's easy enough to deal with if desired by rebuilding the installer from source.

**Comment by clendon-gibson** [comment]
I am OK with closing the ticket, but I want to dispute the use case where USB is used rarely. 

We use cRIOs in a production facilities around the world. RAD will be used to clone the production code onto the cRIO before shipping to a facility. Because newer cRIOs must be programmed via USB when brand new, *every* cRIO prepared for shipping will be programmed via USB. In other words, using the USB interface will occur 100% of the time, not rarely.

**Comment by SparkingSpork** [comment]
> Because newer cRIOs must be programmed via USB when brand new, every cRIO prepared for shipping will be programmed via USB. 

This should be possible over the Ethernet adapters out of the box on all cRIOs. USB definitely is an option we include for convenience, though. This is the first I've heard of that scale of a use case for the USB LAN, so thanks for that feedback!
